### PR TITLE
Svfit

### PR DESCRIPTION
**Pull request by scooperstein**
Hi @isobelojalvo ,

Here's my current code (with a little less junk since I'm now making a pull request from the svfit branch). Since I believe you have a lot of experience with b-tagging, I'm hoping that you can help me make some sense of this error I'm getting while processing the events in my MC (initialization works fine):

An exception of category 'NoProxyException' occurred while
   [0] Processing run: 1 lumi: 40866 event: 16333208
   [1] Running path 'rerun_JetsMC'
   [2] Calling event method for module JetTagProducer/'simpleSecondaryVertexNegativeBJetTags'
Exception Message:
No data of type "JetTagComputer" with label "simpleSecondaryVertex" in record "JetTagComputerRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.

I'm wondering if this is some sort of version compatibility issue with this RecoBTag/Tau stuff. This should have all the relevant tags:

V01-04-08      RecoBTag/ImpactParameter  
V01-08-00      RecoBTag/SecondaryVertex  
V05-08-01      RecoBTag/SoftLepton  
NoTag          RecoBTau/JetTagComputer  
V09-00-01      RecoEgamma/EgammaTools  
METPU_5_3_X_v4 RecoJets/JetProducers  
V04-01-09      RecoLuminosity/LumiDB  
V03-04-07      RecoMET/METAlgorithms  
V15-02-06      RecoParticleFlow/PFProducer  
V01-04-10      RecoTauTag/Configuration  
V01-04-23      RecoTauTag/RecoTau  
V02-02-00      RecoVertex/AdaptiveVertexFinder

Can you check these with yours? I'm assuming that this rerunJetsMC method you have in analysisToolsPT.py is working for you in the UWAnalysis framework, right?

P.S. I think the only relevant change I made to the cmssw packages was switching to using 'selectedPatJets' instead of 'selectedPatJetsPFlow' in RecoJets/JetProducers/python/PileupJetID_cfi

Thanks!
Stephane

### CODE REVIEW

**Comment by scooperstein** [comment]
sorry, the first four tags (the RecoBTag and RecoBTau) packages are the only ones worth checking I think, I added the rest accidentally.

**Comment by scooperstein** [comment]
resolved :)

**Comment by scooperstein** [comment]
Hi @ekfriis , 

Got it working! The only caveat is that you need to comment out the module 'simpleSecondaryVertexNegativeBJetTags' from the schedule in PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cff.py . I talked to @mcepeda and this should be fine for now. Sorry for the clutter, the relevant updated files are:

NtupleTools/python/rerun_JetsMC.py
NtupleTools/test/make_ntuples_cfg.py
PatTools/python/jets/RecoBTag_cff.py 
PatTools/python/jets/patJetPUId_cfi.py

It might be useful to merge these into the master branch as well, since (I believe) the only thing we'd need to change would be getting rid of the svfit option in make_ntuples_cfg.py.

Stephane

**Comment by ekfriis** [comment]
Awesome!  When I have some time this week I will merge it all in.  Thanks
dude!

**Pull request closed without merging**
